#!/bin/bash

#SBATCH --job-name=EMC
#SBATCH --output=EMC-%A_%a.out
#SBATCH --error EMC-%A_%a.out.err
#SBATCH --nodes=1
#SBATCH --ntasks=86
#SBATCH --ntasks-per-node=86
#SBATCH --ntasks-per-socket=43  
#SBATCH --cpus-per-task=1      
#SBATCH --time=24:00:00
#SBATCH --partition=high_priority
#SBATCH --qos=user_qos_timeifler
#SBATCH --account=timeifler

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job NAME is $SLURM_JOB_NAME
echo Slurm job ID is $SLURM_JOBID
echo Number of task is $SLURM_NTASKS
echo Number of cpus per task is $SLURM_CPUS_PER_TASK

cd $SLURM_SUBMIT_DIR
if [ -z "${ROOTDIR}" ]; then
  sleep $(( 5 + SLURM_ARRAY_TASK_ID*25 )) # help avoid different scripts running start_cocoa.sh simultaneously
                                          # clash can still happen when one script runs start_cocoa.sh, the other
                                          # script is reading a file (start_cocoa.sh invokes stop_cocoa.sh)
                                          # which delete links and ROOTDIR so the running script can find file/likelihood
  conda activate cocoa
  source start_cocoa.sh
fi

export OMP_PROC_BIND=close
export OMP_PLACES=cores
export OMP_NUM_THREADS=1
export OMP_DYNAMIC=FALSE
export OPENBLAS_NUM_THREADS=1 
export MKL_NUM_THREADS=1

ulimit -u 2000000 # require line when nmpi is high

"${CONDA_PREFIX}"/bin/mpirun -n ${SLURM_NTASKS} --oversubscribe \
  -x PATH -x LD_LIBRARY_PATH -x PYTHONPATH -x CONDA_PREFIX -x ROOTDIR -x OMP_NUM_THREADS \
  -x OMP_PROC_BIND -x OMP_PLACES -x OMP_DYNAMIC -x CLIK_PLUGIN \
  -x OPENBLAS_NUM_THREADS -x MKL_NUM_THREADS -x CLIK_PATH -x CLIK_DATA \
  --mca mpi_yield_when_idle 1 --rank-by slot --map-by slot \
  --mca pml ob1 --mca btl vader,tcp,self --bind-to core:overload-allowed \
  --mca btl_tcp_if_exclude lo,docker0,virbr0,ib0 --report-bindings \
  python ./projects/roman_real/EXAMPLE_EMUL_EMCEE${SLURM_ARRAY_TASK_ID}.py \
    --root ./projects/roman_real/ \
    --outroot "EXAMPLE_EMUL_EMCEE${SLURM_ARRAY_TASK_ID}" \
    --maxfeval 2000000
